@startuml

abstract class FolderOrFile {
    String name, path
    void getPath()
    String getStringTreeFolder()

}


class Folder{
     void addItem(FolderOrFile fof)
     void removeItem(FolderOrFile fof)
}


class File


Folder *--> File

Folder --|> FolderOrFile
File --|> FolderOrFile
@enduml